# -*- coding: utf-8 -*-
"""
@author: saugata.paul@atos.net
"""

"""
Django settings for mlops_apis project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import random
import string

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

path = os.path.join(BASE_DIR, "my_pat_token.txt")
with open(path, 'r') as file:
    PAT = file.read().replace('\n', '')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'i1l&r+k=-*mgb$!bc(!bi4$bvkdz)6v0@g^c(!r3^vd*5pj_**'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
URI = "https://mlopsws0storageb2304ea4d.blob.core.windows.net/azureml-blobstore-fa9d2517-040e-4c2e-be65-676d5c708710/"

input_params = dict()


#General Project Parameters
input_params['PAT'] = "l2ckn6zjch4hsfjcjtwczznuoozrqafgyaff7cya5m5ru3nwmfuq" #For AZURE
input_params['MY_CONNECTION_STRING'] = "DefaultEndpointsProtocol=https;AccountName=mlopsws0storageb2304ea4d;AccountKey=R+Xi41FFV0AT4VcsaLzrZBT3ya0qtn9VZs5UQ8wF9hVMBK5k6YRj881/Tygg7t75X3hE610MVHi+f5C13k5jkg==;EndpointSuffix=core.windows.net"
input_params['CONTAINER_NAME'] = "azureml-blobstore-fa9d2517-040e-4c2e-be65-676d5c708710"
input_params['DEFAULT_BLOB'] = "workspaceblobstore"
input_params['SUBCRIPTION_ID'] = "b53cd405-74a5-4714-9549-88af4dc84f66"
input_params['ORGNIZATION_URL'] = "https://dev.azure.com/SyntbotsAI-RnD/"
input_params['PROJECT_NAME'] = "Assisted-MLOPs"
input_params['PIPELINE_ID'] = 18

#Pipeline Parameters
input_params['computeIdleSecs'] = 350
input_params['computeMaxNodes'] = 3
input_params['computeMinNodes'] = 0
input_params['region'] = "centralindia"
input_params['resourceGroup'] = "SyntbotsAI-RnD-MLOps"
input_params['workspace'] = "MLOps_WS01"
input_params['system_debug'] = True
input_params['aks_clusterPurpose'] = "DevTest"
input_params['aks_agentCount'] = 3
input_params['path_data_process'] = "/home/azureuser/AMLops_Agent/myagent/tempdatastore/"
input_params['path_artifact'] = "/home/azureuser/AMLops_Agent/myagent/tempdatastore/"
input_params['save_train_script_location'] = os.path.join(BASE_DIR, 'training.py')
input_params['save_preprocess_script_location'] = os.path.join(BASE_DIR, 'prepocess_script.py')

#Create Dataset Registry, Training, Deployment params based on dataset name
input_params['train_stage_source_directory'] = "."
input_params['train_stage_training_script_name'] = "training.py"
input_params['train_stage_artifact_loc'] = "./output/models/"
input_params['data_dir_location'] = "dataset"
input_params['train_stage_environment_setup_path'] = 'environment_setup'
input_params['register_model_model_asset_path'] = "output/models/"
input_params['register_model_tag'] = "ML Model"   

input_params['yaml_template_location'] = os.path.join(BASE_DIR, 'yaml_templates/training/azure-pipelines.yml')
input_params['yaml_output_folder_location'] = os.path.join(BASE_DIR, 'yaml_outputs/training')
input_params['preprocess_file_location'] = os.path.join(BASE_DIR, 'yaml_outputs/training/prepocess_script.py')
input_params['training_file_location'] = os.path.join(BASE_DIR, 'yaml_outputs/training/training.py')

input_params['train_config_location'] = os.path.join(BASE_DIR, 'yaml_templates/training/iris_training.runconfig')
input_params['train_config_save_location'] = os.path.join(BASE_DIR, 'yaml_outputs/training/')

#Conda Dependency
input_params['conda_config_location'] = os.path.join(BASE_DIR, 'yaml_templates/training/conda_dependencies.yml')
input_params['conda_config_save_location'] = os.path.join(BASE_DIR, 'yaml_outputs/training/')

#Smoke
input_params['smoke_test_file_template_location'] = os.path.join(BASE_DIR, 'yaml_templates/training/smoke_tests.py')
input_params['smoke_test_file_save_location'] = os.path.join(BASE_DIR, 'yaml_outputs/training/smoke_tests.py')

#Score
input_params['score_file_template_location'] = os.path.join(BASE_DIR, 'yaml_templates/training/score.py')
input_params['score_file_save_location'] = os.path.join(BASE_DIR, 'yaml_outputs/training/score.py')

#AMLOPS JSON
input_params['save_config_location'] = os.path.join(BASE_DIR, 'yaml_outputs/training/amlops_config.json')

input_params['pipeline_description'] = "Assisted_MLOPS Pipeline"
input_params['yaml_path'] = "./azure-pipelines.yml"
input_params['project_name'] = input_params['PROJECT_NAME']
input_params['repo_branch'] = "master"
input_params["original_pipeline_repo_url"] = "https://SyntbotsAI-RnD@dev.azure.com/SyntbotsAI-RnD/Assisted-MLOPs/_git/Assisted-MLOPs"
input_params['ServiceConnection_NAME'] = "Azure subscription 1"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mlops_apis_azure',
    'corsheaders',
    'mlops_apis',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "content-range",
    "content-disposition",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "cache-control",
    "pragma",
]


ROOT_URLCONF = 'mlops_apis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mlops_apis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'


# CELERY STUFF
BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'

CELERY_DEFAULT_QUEUE = 'azure_async_q'
CELERY_DEFAULT_EXCHANGE = 'azure_async_q'
CELERY_DEFAULT_ROUTING_KEY = 'azure_async_q'